### ISSUE TITLE
Dataflow - generating false alerts

### ISSUE THREAD

**Issue by karankap** [oracle-devrel/oci-wearable-health-app#19]
2 issues with the dataflow job:

- Sometimes generating alerts even for those devices that are not sending data 
- iGenerating multiple alerts for the same parameter with-in the same window.

**Comment by anilcourse** [comment]
1. It looks like Spark job takes care of old event which arrives late to it as it checks for event arrival time and include it in that window and updates dataframe so that it reflects correctly . We can implement watermarking so that we can discard event if it arrives to Spark job after certain time (e.g. 2 hours /4 hours etc. ) or we want to include it even if it arrives late ?

2. It looks like The current frequency is 2 mins but notification app sends  in every 5 mins so there can be more than one message in the window of 5 mins  for the same device/user. I am just wondering if we match the frequency of Spark job with notification app or should we tweak our windowing strategy.

**Comment by karankap** [comment]
The issue has been fixed, it was happening due to missing watermark in the dataflow job.
